name: waterxpress_customer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  flutter_screenutil: ^5.9.3
  curved_labeled_navigation_bar: ^2.0.5
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  get_storage: ^2.1.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  url_launcher: ^6.0.10
  progress_tracker: ^0.0.12
  intl: ^0.20.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
